### ISSUE TITLE
Something is up with the tag/version

### ISSUE THREAD

**Issue by leowebguy** [resolvetosavelives/healthicons#195]
![Screenshot 2024-02-08 at 9 08 14 AM](https://github.com/resolvetosavelives/healthicons/assets/8460020/7aa58be9-2adf-4c8c-a1ca-b701a369e50f)

For now I've switched to "dev-main" , but a release would be better.

**Comment by dburka** [comment]
Thanks so much for reporting @leowebguy! Hey @nburka @gauthierm , could we look into this, please?

**Comment by nburka** [comment]
Hey @leowebguy - what are you trying to do? I just took a look, and the package.json version number hasn't been updated for 3 years since we launched the project. It's been `0.1.0` the whole time. The project isn't very well set up to be installed via NPM because it also includes the entire website and not just the icons.

We actually had a PR submitted to make the icons publishable via NPM here https://github.com/resolvetosavelives/healthicons/pull/185#issuecomment-1607875613 but it didn't have a way to resolve the website/nextJS issue.

I _think_ the ideal solution would be something like publishing all of the icons in one repo, and then installing that in a separate website repo. But that would make the management of the website more difficult of the designers who have limited git experience. Any suggestions you have would be appreciated.

**Comment by nburka** [comment]
@gauthierm do you have any insight on the best way to restructure things so that:
 - people who just want the icons can install the icons package
 - we still have the website in a repo
 - there's a very easy way to use `yarn` to download the latest icons from Figma, update the icons (maybe in their own repo), release an npm package with updated version number, while also updating the website and releasing it.

**Comment by nburka** [comment]
Yeah, maybe the way to handle it is just to split the repos. So we'd have:
 - `resolvetosavelives/healthicons` which would just have the icons
 - `resolvetosavelives/healthicons-website` which would have the website with the icons installed via the npm package

So to release new icons, we'd need to:
 1.  in the "icons" repo, run `yarn update-icons` like we currently do
 2. add new instructions on how to release the NPM package or just add a step like `yarn release` or something
 3. switch to the "website" repo and `yarn upgrade healthicons`
 4. make a PR and merge

It'll be a bit more confusing, but not too bad. As long as we can make it relatively easy to update the package version numbers.

**Comment by nburka** [comment]
Another solution would be what was suggested in the other PR https://github.com/resolvetosavelives/healthicons/pull/185#issuecomment-1948702517

Moving all dependencies into `devDependencies`. Because the website is published as static HTML, this would work. But, if we ever wanted to move to a full NextJS release, I don't think it would work.

**Comment by nburka** [comment]
Hey @leowebguy - this should now be resolved!! I've merged the PR that cleans up the NPM package. I also released a 1.0.1 release. We will start releasing new icons with new version numbers in the future.
